services:
  database:
    image: postgres:17-alpine3.21
    restart: unless-stopped
    container_name: arcana_database
    expose:
      - 5432:5432
    env_file:
      - .env.production
    volumes:
      - arcana_pg_data:/var/lib/postgresql/data

volumes:
  arcana_pg_data:
