include:
  - ./docker-compose.infra.yml

services:
  arcana:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.application
    container_name: arcanapixel_app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ..
      dockerfile: ./infra/Dockerfile.server
    container_name: arcanapixel_server
    # ports: # Don't need ports, this is proxied through /api endpoint in the frontend
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - .env.production

volumes:
  caddy_data:
  caddy_config: