#!/usr/bin/env sh

set -e # Exit on error

# Change to the repository root directory
cd "$(git rev-parse --show-toplevel)"

if [ -n "$(git diff --staged --name-only -- apps/application/)" ]; then
  pnpx turbo format --filter=@arcana-pixel/application
fi

if [ -n "$(git diff --staged --name-only -- apps/server/)" ]; then
  pnpx turbo format --filter=@arcana-pixel/server
fi

if [ -n "$(git diff --staged --name-only -- apps/docs/)" ]; then
  pnpx turbo format --filter=@arcana-pixel/docs
fi

if [ -n "$(git diff --staged --name-only -- apps/website/)" ]; then
  pnpx turbo format --filter=@arcana-pixel/website
fi

if [ -n "$(git diff --staged --name-only -- apps/website/src/routes/)" ]; then
  cd apps/website/ && pnpm generate-sitemap && cd ../../
fi

if [ -n "$(git diff --staged --name-only -- packages/schemas/)" ]; then
  pnpx turbo build --filter=@arcana-pixel/schemas
fi

git add .
